// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJPJ-_DThCiQN15GZEY7RHHOfWNV3gHA',
    appId: '1:415523442279:web:843fd9817cf993a0fb8ec2',
    messagingSenderId: '415523442279',
    projectId: 'tripeka-mobile',
    authDomain: 'tripeka-mobile.firebaseapp.com',
    storageBucket: 'tripeka-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtM7df73Nw-p-3YEmywFRjjqvkCCrwcE0',
    appId: '1:415523442279:android:f19ed8cb1627dd67fb8ec2',
    messagingSenderId: '415523442279',
    projectId: 'tripeka-mobile',
    storageBucket: 'tripeka-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaEfQ94uQvYVQTDvZ1z6a4uO3LxwOAQSI',
    appId: '1:415523442279:ios:0555a6857323460dfb8ec2',
    messagingSenderId: '415523442279',
    projectId: 'tripeka-mobile',
    storageBucket: 'tripeka-mobile.appspot.com',
    iosClientId: '415523442279-k1v968n1ir467mll3n6lo01dnfthtchb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaEfQ94uQvYVQTDvZ1z6a4uO3LxwOAQSI',
    appId: '1:415523442279:ios:0555a6857323460dfb8ec2',
    messagingSenderId: '415523442279',
    projectId: 'tripeka-mobile',
    storageBucket: 'tripeka-mobile.appspot.com',
    iosClientId: '415523442279-k1v968n1ir467mll3n6lo01dnfthtchb.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
